# Generated by Django 4.2.15 on 2024-08-09 19:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_song_Json',
            field=models.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_song_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=6, unique=True),
        ),
    ]
