# Generated by Django 4.2.15 on 2024-08-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_last_song_json_room_last_song_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_song_Json',
            field=models.JSONField(null=True),
        ),
    ]
